/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel;

import hotelappfit5148.Database;
import hotelappfit5148.ErrorMessage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author thaonguyen
 */
public class InsertUpdateHRoomDialog extends javax.swing.JDialog {

    private RoomBean room;

    /**
     * Creates new form InsertUpdateHRoomDialog
     */
    public InsertUpdateHRoomDialog(RoomBean roomTempt, String action) {
//        super(parent, modal);
        initComponents();
        if (ErrorMessage.UPDATE_ACT.equals(action)) {
            viewHotelDetail(roomTempt);
            newRoomjButton1.setVisible(false);
        } else {
            updateRoomjButton2.setVisible(false);
        }
    }

    private void viewHotelDetail(RoomBean roomTempt) {
        this.room = roomTempt;
        this.hotelIdText.setText(room.getHotelId().toString());
        this.roomNumberText.setText(room.getRoomNumber());
        this.roomTypejComboBox1.setSelectedItem(room.getRoomType());
        this.priceText.setText(Float.toString(room.getPrice()));
        this.descriptionTextArea.setText(room.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomNumberLabel = new javax.swing.JLabel();
        roomNumberText = new javax.swing.JTextField();
        hotelIdLabel = new javax.swing.JLabel();
        hotelIdText = new javax.swing.JTextField();
        roomTypeLabel = new javax.swing.JLabel();
        roomTypejComboBox1 = new javax.swing.JComboBox();
        priceLabel = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        newRoomjButton1 = new javax.swing.JButton();
        updateRoomjButton2 = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roomNumberLabel.setText("Room Number *");

        hotelIdLabel.setText("Hotel ID *");

        roomTypeLabel.setText("Room Type");

        roomTypejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Studio", "Suite" }));

        priceLabel.setText("Price *");

        priceText.setText("0");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        descriptionLabel.setText("Description");

        newRoomjButton1.setText("New Room");
        newRoomjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoomjButton1ActionPerformed(evt);
            }
        });

        updateRoomjButton2.setText("Update Room");
        updateRoomjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoomjButton2ActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newRoomjButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateRoomjButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomNumberLabel)
                            .addComponent(hotelIdLabel)
                            .addComponent(roomTypeLabel)
                            .addComponent(priceLabel)
                            .addComponent(descriptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(roomNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(hotelIdText))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roomTypejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNumberLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(hotelIdLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hotelIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeLabel)
                    .addComponent(roomTypejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(descriptionLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateRoomjButton2)
                    .addComponent(CancelButton)
                    .addComponent(newRoomjButton1))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newRoomjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoomjButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertUpdateHRoomDialog(null, ErrorMessage.INSERT_ACT).setVisible(true);
            }
        });
    }//GEN-LAST:event_newRoomjButton1ActionPerformed

    private void updateRoomjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRoomjButton2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:

        // TODO add your handling code here:
        if (hotelNameText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter required fields.");
            return;
        }
        if (emailText.getText().trim().contains("@") == false) {
            JOptionPane.showMessageDialog(null, "Please enter correct email.");
            return;
        }

        try {
            hotel.setAddress(addressText.getText().trim());
            hotel.setCity(cityText.getText().trim());
            hotel.setConstructionYear(Integer.parseInt(constructionYearText.getText().trim()));
            hotel.setContactNumber(contactNumberText.getText().trim());
            hotel.setCountry(countryText.getText().trim());
            hotel.setEmail(emailText.getText().trim());
            hotel.setHotelName(hotelNameText.getText().trim());
            hotel.setHotelType(String.valueOf(typeComboBox.getSelectedItem()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please enter correct data type.");
            return;
        }
        PreparedStatement preparedStatement = null;
        Connection dbConnection = Database.getInstance().getDBConnection("FIT5148A");
        String insertTableSQL = "update  hotel set "
                + "hotel_name = ?, hotel_type = ?, construction_year = ?, "
                + "country = ?, city = ?, address = ?, contact_number = ?, email = ? where hotel_id = ?";

        try {
            preparedStatement = dbConnection.prepareStatement(insertTableSQL);
            preparedStatement.setString(1, hotel.getHotelName());
            preparedStatement.setString(2, hotel.getHotelType());
            preparedStatement.setInt(3, hotel.getConstructionYear());
            preparedStatement.setString(4, hotel.getCountry());
            preparedStatement.setString(5, hotel.getCity());
            preparedStatement.setString(6, hotel.getAddress());
            preparedStatement.setString(7, hotel.getContactNumber());
            preparedStatement.setString(8, hotel.getEmail());
            preparedStatement.setLong(9, hotel.getHotelId());
            preparedStatement.executeUpdate();

            JOptionPane.showMessageDialog(null, "Update successfully.");
            preparedStatement.close();
            Database.getInstance().closeDBConnection();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        this.dispose();
    }//GEN-LAST:event_updateRoomjButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertUpdateHRoomDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertUpdateHRoomDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertUpdateHRoomDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertUpdateHRoomDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                InsertUpdateHRoomDialog dialog = new InsertUpdateHRoomDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel hotelIdLabel;
    private javax.swing.JTextField hotelIdText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newRoomjButton1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceText;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JTextField roomNumberText;
    private javax.swing.JLabel roomTypeLabel;
    private javax.swing.JComboBox roomTypejComboBox1;
    private javax.swing.JButton updateRoomjButton2;
    // End of variables declaration//GEN-END:variables
}
